# Exos :

### Partie Numpy

In [99]:
import numpy as np
import matplotlib.pyplot as plt

In [100]:
# 1.

#array_int = np.array(range(1, 11)) # fonctionne mais à améliorer
array_int = np.arange(1, 11)
array_int

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
# 2.

arr = np.random.rand(5)
arr

array([0.63133243, 0.86486002, 0.40786628, 0.85557567, 0.1713253 ])

In [102]:
# 3.

arr = np.random.randn(10)
print(arr)

def sum_array(arr):
    sumarray = arr.sum()
    return sumarray
sum_array(arr)

[-0.34860296  1.4634334  -0.86955037 -1.82303871 -0.71733781 -1.09569354
 -1.4357297  -1.43080839 -1.37598937  0.66343061]


-6.969886828920126

In [103]:
# 4.

arr1 = np.random.randn(10)
arr2 = np.random.randn(10)
def arr_dot(arr1, arr2):
    arr_scal = np.dot(arr1, arr2)
    return arr_scal
arr_dot(arr1, arr2)


3.4193296418291013

In [104]:
# 5.

arr3 = np.array([1, 2, 3, 2, 3, 5, 1, 12, 25])
def arr_unique(arr):
    arruni = np.unique(arr)
    return arruni
arr_unique(arr3)

array([ 1,  2,  3,  5, 12, 25])

In [105]:
# 6.

arr4 = np.random.randn(10)
def arr_incr(arr):
    arrincr = np.sort(arr)
    return arrincr
arr_incr(arr4)

array([-1.81569816, -1.28372344, -1.11896981, -1.02303971, -0.15813726,
        0.23363471,  0.78013648,  1.29051363,  1.80742801,  1.92536017])

In [106]:
# 7.

arr5 = np.random.randn(10)
def arr_stats(arr):
    arrmean = np.mean(arr)
    arrmed = np.median(arr)
    arrsd = np.std(arr)
    return arrmean, arrmed, arrsd
arr_stats(arr5)

(0.21249053550683122, 0.42107394361763717, 1.0062178043614887)

In [107]:
# 8.

arr6 = np.arange(-16, 16)
def arr_replace(arr):
    arr[arr < 5] = 0
    arr[arr >= 5] = 1
    return arr
arr_replace(arr6)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [108]:
# 9.

from sympy import isprime
arr7 = np.arange(1, 20)
def arr_primenum(arr):
    arrprimenb = np.array([x for x in arr if isprime(x)])
    return arrprimenb
arr_primenum(arr7)


array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [109]:
# 10.

arr2D = np.random.randint(1, 10, size = (3, 3))
arr2D

array([[4, 3, 6],
       [4, 6, 4],
       [7, 7, 5]])

### Partie Graphique

In [110]:
import numpy as np
import matplotlib.pyplot as plt

In [111]:
# 1.

